name: Initialize From Template

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/init-project.yml'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Use common init action
        uses: Event-Based-Banking-Application/arya-banking-workflows/.github/actions/init-project@main
