name: Initialize Repo From Template

on:
  push:
    branches:
      - master
    paths:
      - 'pom.xml'
      - 'src/**'

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run shared init script
        uses: Event-Based-Banking-Application/arya-banking-workflows/.github/actions/init-project@main
